### ISSUE TITLE
Honeymoon

### ISSUE THREAD

**Issue by brianamarie** [brianamarie/Wedding#15]
We're going to Iceland! 
#### Monday, July 25

DELTA 959 MAIN CABIN (T)
KANSAS CITY, MO 5:06pm
MPLS-ST PAUL 6:30pm

DELTA 260 MAIN CABIN (T)
MPLS-ST PAUL 9:55pm 
REYKJAVIK, ICELAND 9:00am **Tue 26JUL
#### Friday, July 29

DELTA 261 MAIN CABIN (T)
REYKJAVIK, ICELAND 8:30am
MPLS-ST PAUL 10:00am

DELTA 2111 MAIN CABIN (T)
MPLS-ST PAUL 1:05pm
KANSAS CITY, MO 2:24pm
## Hotel

Check-in:  
Tuesday, July 26, 2016 (15:00 )
Check-out:  
Friday, July 29, 2016  ( 12:00)
Hotel Address:  Thórunnartún 4
Reykjavík, 105, Iceland

Hotel Phone Number: +3545183000
Number of Rooms:  
1 Room
Reservation Name:  
Room 1: Christopher Williams 

Booking Partner:  
Booking.com
Booking Number and PIN Code:  
908386756 (PIN Code: 6831)
## Rental Car

Dear Mr Christopher Williams
Thank you for renting a car with Budget Car Rental. Information regarding your booking can be viewed below.

Please print this out and carry with you to your rental station. Have a nice trip.
Your Personal Details
Name:   Christopher Williams
Address:    523 S Burno Dr.
60067 Palatine
United States Illinois
Contact:    417-224-0044
Credit Card:  
About Your Rental
Reservation No: 3480-8234-IS-6
Rental Location:    Reykjavik, Reykjavik Domestic Airport

Telephone ( 354-5626060 )
Return Location:    Reykjavik, Reykjavik Domestic Airport

Telephone ( 354-5626060 )
Date of Rental: 26 July 2016 10:00
Opening hours on day of pickup: 08:00-18:00 hours
Date of Return: 28 July 2016 19:00
Opening hours on day of return: 08:00-18:00 hours
Car Group:  Group O - e.g. Hyundai i20 Auto or similar
Amount: 341.75 EUR
Additional Information
Rental Price to be Paid:    45,100.00 ISK
Your Quote Includes:  
Local Tax (TAX)
Collision Damage Waiver (CDW)
Vehicle Registration Fee (VRF)
Airport/city surcharge
Unlimited Mileage
Additional Costs:   

Damage Excess: 195000.- ISK
Theft Protection Excess: 195000.- ISK
- [x] Print off email and bring to rental car location
- [ ] When picking up car, ask for them to pick up the car from hotel Thursday evening.
## Activities
- [x] Find activities and book 'em! 
  - Hot springs ♨️ 
  - Hiking 👢 
  - Whale watching? 🐳 
  - Pub crawl? 🍺 

@C-Williams What do you think? 

@allthedoll Heya! 👋 I know you ❤️ Iceland and planning trips, but I also know you've had some crazy stuff happen this week.  If you are feeling up to it, we would very much appreciate help and advice in where/how to book things like a car and activities. BUT Please feel no pressure to help because I want you to focus on healing!

**Comment by brianamarie** [comment]
@elizabethn I saw your comment in Slack about wanting to Honeymoon in Iceland. I'm about to do just that and this is where we plan to keep...plans. 😄 Just a friendly FYI

**Comment by ElizabethN** [comment]
@brianamarie omg this is amazing! I will absolutely stalk this repo now. (We also used GitHub to plan our wedding, lol. :dancer: )

**Comment by allthedoll** [comment]
@allthedoll's Iceland pro tipz:
**Overview:**
Rent a car. I don't know if Iceland even has automatic vehicles, so I hope you or someone going can drive a manual transmission. If you are going in the winter, when the winds are *really* strong (70+ mph), make sure you're really comfortable driving in those conditions as white outs due to wind are common, and Icelanders are used to it so they don't even slow down. I tend to go in the fall and winter to avoid crowds of festival-goers from abroad.

I'm going to highlight *some* things, but my biggest recommendation is to get a car, and just drive south on highway one, and do the Golden Circle. While I personally spend most of my time in Suðurland (South) and Austurland (east), there isn't an area of Iceland I haven't loved, and many people really enjoy Norðurland (North) -- especially Akureyri, which is the second-largest city. It's possible to go around the entirety of Iceland in 10 days, but you'd be rushing and missing cool side trips. The best part, in my opinion, about the south is that it's very wild, rugged, and has lots of cool shit in a concentrated area--things tend to be a bit more spread out in the north.

**Reykjavík:** 1 day
I actually haven't spent much time here because I don't go to Iceland for the city. 😛 My friend Auður's company does city tours, but I've never actually done it. I assume they're good because she's awesome. I think they book fast, though. See resources for info.
- [Hallgrímskirkja](https://en.wikipedia.org/wiki/Hallgr%C3%ADmskirkja) is a landmark
- [Kolaportið](http://www.iheartreykjavik.net/2012/05/kolaportid-flea-market/) is a rad flea market near the water. I've found great turn-of-the-century postcards, and great Icelandic poetry books (which might not interest you if you can't read Icelandic?) there. You can also try fermented shark, which is a delicacy. I'm vegetarian and some Icelanders do not care for it; those that do, really do.
- Alcohol is extremely expensive due to prohibition-era laws (beer was illegal until 1989!).
  - Consider trying [Brennivín](https://en.wikipedia.org/wiki/Brenniv%C3%ADn), which you can also buy at the duty free in the airport.
 - This [guide to drinking in Iceland](http://warontherocks.com/2015/09/your-guide-to-drinking-in-iceland/) seems to know what's up.


**Golden Circle** - 1 day
The Golden Circle has three major attractions, but the entire drive is beautiful in any season. You can do excursions, if that is your thing, which includes scuba diving in TÞingvellir depending on the season. 
- [Geysir™](https://en.wikipedia.org/wiki/Geysir) as in the originally documented geyser, from where all other geysers get their name.
- [TÞingvellir](https://en.wikipedia.org/wiki/%C3%9Eingvellir) is one of two places in the world where you can see tectonic plates *pulling apart* (vs pushing together, as in mountains). They recently made a tourist vista at the top, which overlooks Þingvallavatn, a large lake. Sunset here is amazing over the valley, and the colors reflect over the waters. Legit photo op.
- [Gullfoss](https://en.wikipedia.org/wiki/Gullfoss)

**Reykjavík to Vík í Mýrdal, Suðurland (South):** 2 days
Vik (Veek) is the southern-most town on the island, and is quite small and lovely. It is home to icelandic wool industry, and there is a shop you can visit and watch them work, and buy goods. There are a few road-side sites you'll see; I suggest stopping at all of them. You'll know when you see them.
- Hot springs: [Seljavallalaug](http://www.iheartreykjavik.net/2013/05/seljavallalaug-a-hiidden-gem-in-south-iceland/) and [Hveragerði](http://besthiking.net/hveragerdi-hot-spring-river-trail-hiking-iceland/)
- Take the ferry from Landeyjahöfn (nice black sand beach here) to [Heimaey](https://en.wikipedia.org/wiki/Heimaey) in [Vestmannaeyjar](https://en.wikipedia.org/wiki/Vestmannaeyjar) (the Westman Islands). It's about 1.5 hours on the boat; take your car.
  - If it's [puffin season](http://visitwestmanislands.com/page/baby-puffins-in-westman-islands) there is a cliff to walk to where they nest. Town children catch loose pufflings and return them. The view there of the other, smaller islands is wonderful.
  - Drive around! If it looks like a road, unless it's marked private, you can drive it. If it looks like tire paths, you can drive it. Just don't be dumb. Disclaimer: we've definitely driven over more than one volcano both here and on the mainland...
  - Go to [Eldfell](https://en.wikipedia.org/wiki/Eldfell), and see the stave marking the site of a [church](https://www.google.com/maps/place/63%C2%B026'03.6%22N+20%C2%B015'04.7%22W/@63.434347,-20.2534947,383m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d63.434347!4d-20.251306) that was buried in the island's volcanic eruption of 1973. Islanders and mainlanders in the south are very sensitive about this eruption as it devastated the island and they received little support.
  - Follow all of the "roads" out this way as there are some neat things to discover, that I won't spoil here. The area is very Martian meets Wes Anderson.
- See the plane crash at [Sólheimasandur](https://www.google.com/maps/place/Solheimasandur+Plane+Wreck/@63.4591959,-19.366435,444m/data=!3m1!1e3!4m5!3m4!1s0x0:0xde6566d286cc57f7!8m2!3d63.4590918!4d-19.3647122). It's okay to drive on the rocks, just be careful; a farmer owns this property and doesn't mind people going.
- Follow [Reynishverfisvegur](https://www.google.com/maps/place/Reynishverfisvegur,+Iceland/@63.4294904,-19.121478,12z/data=!4m5!3m4!1s0x48d74a1be40cc4e7:0xf1235324a83b86c3!8m2!3d63.4294904!4d-19.0514402) to the basalt rocks on the beach near Vík. Look for the cave of basalt and mind the rogue waves. If you went into any book or gift shops in Reyjkavík, you might have noticed a condom with a picture of a penis-shaped seastack, which is in this area. You're welcome.

**Vík to Höfn (Hoep; means harbor):** 2 days
- [Jökulsárlón](https://en.wikipedia.org/wiki/J%C3%B6kuls%C3%A1rl%C3%B3n) is the glacier lagoon. Use extreme caution if you are not using a guide, and if you are inexperienced then do not enter it without a guide. You can go and look, though.
- If you go to Iceland in winter, you can explore an ice cave or walk on a glacier; in the spring they do guided hikes. Have a shameless plug for my friend [Aron Franklin Jonsson](http://www.glacierguides.is/).
  - Please note if going winter hiking alone: even if you have extensive experience and proper equipment, the terrain can be tough; your partner will not pack your headlamp; you will not double-check your bag because you're demonstrating how much you trust him; the sun will go to sleep sooner than you think; and your crampons can not save you from mountaineering ice in the dark, and you will sprain your wrist in a major way; there will be no clinics or pharmacies with the kind of brace you need to avoid permanent damage...
- [Svartifoss](https://en.wikipedia.org/wiki/Svartifoss) (black falls) is a waterfall with basalt rock in Skaftafell, inside Vatnajökulsþjóðgarður (Vatnajökull National Park)

**Side notes:**
- Skip Blue Lagoon and go to a non-tourist hot spring instead. Disclaimer: I've never been to the Blue Lagoon! I know people that have been and loved it. If you consider yourself very much a tourist, then you probably will.
- There will be sheep in the road.
- Reindeer can usually only be seen in Austurland (East) and on F-roads in central Iceland (summer only). Fun fact: arctic foxes are the only native mammal.
- There are little to **no** trees because it's too windy for them to grow.
- You will not see northern lights in the summer because daylight lasts 24 hours. If you desire to see them, I suggest going in February--see my thing about driving in heavy winds! I have a great video of giant chunks of ice flying at us as we try pumping petrol.
- Have a variety of credit cards as some gas stations are weird with them. If a gas station is open when you go to one, maybe buy a gas gift card to avoid late night problems.
- Have some krona and change for parking in the city, and for flea markets (some take cards).
- Have a rough guide to the exchange rate (e.g. $1=122, $10=1220, $25=3055, $50=6101), as cell service in the south can be spotty and data expensive (if you get an [Icelandic sim card](http://www.iheartreykjavik.net/2016/01/5-reasons-why-you-should-consider-buying-an-icelandic-sim-card-for-your-trip-to-iceland/)). 
- Take snacks in your car because, depending on the time of year, finding food can be difficult. This might just be because we're vegetarian and Iceland is very much a meat-oriented place (boiled sheep head and hot dogs). We also go to remote places at odd hours.
- Most everyone speaks some English, if not fluently.
- If weather seems a bit bad, stop in a gas station and ask the locals if there is a storm. Sometimes they will recommend getting off the road asap, and you will knock on a random farmhouse to stay with a random Icelandic family and wind up feeding their cows in the morning.
- Be mindful of wind knocking open the doors of your rental car, so hold the door carefully until it's closed again. For real.

**Vocabulary break-down:**
These are useful key pre and suffixes when reading roadsigns. If you see a green sign with crazy arrows, it's a map to farms. Sometimes there are hidden sites.
- foss = waterfall
- fell = landscape feature (e.g. scenic area)
- jökull = glacier
- höfn = harbor

**Resources:**
- [I ❤️ Reykjavík](http://www.iheartreykjavik.net/) is a blog written by my friend Auður; she's native.
- Use booking.com to find hotels along the way, but book directly with the hotel if you can so booking.com doesn't shave 15% and you support the locals; most farms now have hotels because it brings in more steady money in the spring and summer, which sustains them in winter.

@jordanmccullough has also been at least once, maybe he also has suggestions?

**Comment by allthedoll** [comment]
@brianamarie I know you already booked, but I definitely recommend not staying in Reykjavik the entire time because a lot of the cooler places to see are a drive.

Where to stay near Vík: http://www.guesthousesteig.is/
 - Say hi to Gremlin (dog) for me.
 - The owner is a spiritual healer.
Where to stay near Höfn: http://www.skalafell.net/
 - Say hi to Katja (dog) for me.

**Comment by brianamarie** [comment]
@allthedoll YOU ARE MY HERO!!!!!!!!!!

**Comment by brianamarie** [comment]
![screen shot 2016-07-13 at 4 26 34 pm](https://cloud.githubusercontent.com/assets/9906718/16820450/a6da4c18-4916-11e6-9a4e-0b6a72b3b850.png)

**Comment by brianamarie** [comment]
[travelinsurance.pdf](https://github.com/brianamarie/Wedding/files/363947/travelinsurance.pdf)

@C-Williams It's a good thing my order for travel insurance didn't go through - it turns out you already got it! :)

**Comment by C-Williams** [comment]
Preliminary Plan - 

Tue, July 26

- [ ] Land 9:30
- [ ] Hallgrímskirkja (Big church)
- [ ] Kolaportið (Big flea market)
- [ ] Museums in the area
   - [ ] https://guidetoiceland.is/reykjavik-guide/top-6-museums-in-reykjavik
- [ ] Bar hopping
   - [ ] Kaffibarinn
   - [ ] Kex Hostel
   - [ ] Micro Bar
   - [ ] Snaps, more of a restaurant
   - [ ] Kaldi
   - [ ] Ölstofa Kormáks og Skjaldar

Wed, July 27

- [ ] Golden Circle!
   - [ ] http://expertvagabond.com/golden-circle-iceland/
   - [ ] https://www.google.com/maps/dir/Reykjavik,+Iceland/Thingvellir+National+Park,+South,+Iceland/Geysir,+South,+Iceland/Gullfoss,+South,+Iceland/Keri%C3%B0,+Iceland/Reykjavik,+Iceland/@64.1354443,-22.0906322,8z/am=t/data=!3m1!4b1!4m38!4m37!1m5!1m1!1s0x48d674b9eedcedc3:0xec912ca230d26071!2m2!1d-21.8174393!2d64.1265206!1m5!1m1!1s0x48d6810d7c1f5efb:0x7b12e3a7b1a1e85!2m2!1d-21.079623!2d64.266283!1m5!1m1!1s0x48d6a39942556af3:0x351893d2f72be313!2m2!1d-20.2995425!2d64.3138792!1m5!1m1!1s0x48d6a574b42e3e67:0xc66d192597a540be!2m2!1d-20.121331!2d64.327751!1m5!1m1!1s0x48d68bb755f6f257:0x515a44e0c12ed907!2m2!1d-20.8851385!2d64.0412777!1m5!1m1!1s0x48d674b9eedcedc3:0xec912ca230d26071!2m2!1d-21.8174393!2d64.1265206!3e0
- [ ] Hopefully that link works...

Thur, July 28

- [ ] Whale watching!!
   - [ ] http://lakitours.com/our-tours/summer-whale-watching/
      - [ ] About a 2 1/2 hr drive, have availability Tues, Wed and Thur still, should act fast

We can change the order of these so that we can return the car at an appropriate time. @brianamarie What do you think???

**Comment by brianamarie** [comment]
Even though we didn't plan perfectly for the cell phone portion, the trip is off to a great start! 🎉 

We landed in Keflavik airport and had a beautiful drive up to Reykjavik. We took a scenic route past  some springs, which got me very excited for hot springing tomorrow. The color of the water is so backwards because it's so bright! 

Luckily the car rental place worked with us - we accidentally booked a rental out of Reykjavik airport, not knowing we were flying into a different city about 30-45 minutes away. We also rented a navigation system, which has proven super helpful. We found our hotel, Storm Hotel, and walked down the street to Cafe Johansen for some delicious lunch. I think we ate some chicken stir-fry with rice. (P.S. Iceland tap water is DELICIOUS)

We checked into our hotel (which has free parking) and immediately took a long nap - like 2.5 or 3 hours. Chris DID NOT want to wake up, but I made him anyway at about 5:45 PM so we could get dinner. He was very sleep angry. 

We went to a nearby restaurant called Pulsa which served different types of bratwurst. I got a pork/beef brat with mustard (SO GOOD MUSTARD) and a potato/egg salad on the side. Chris got a duck brat with mashed potatoes and some radish sauce. Both were delicious. We also drank some black saisons, a type of beer neither of us had tried before.

We walked back to the hotel and are planning on stopping by the hotel bar and using some of our free drink vouchers (I told the guy checking us in that it was our honeymoon) and trying to turn in for the night.

🍧 Iceland is very fun so far!!! People so nice 😽

**Comment by storbeck** [comment]
Are you still there or can this issue be closed?

**Comment by allthedoll** [comment]
I'm still there. I'm never coming back, NEVER.

**Comment by brianamarie** [comment]
> Are you still there or can this issue be closed?

Issues can be closed?
